name: SDv1.5mv-rawbox-t
pretrained_model_name_or_path: ./pretrained/stable-diffusion-v1-5/
bbox_mode: 'all-xyz'
bbox_view_shared: false
crossview_attn_type: basic
train_with_same_noise: false
train_with_same_t: true

# temporal
load_pretrain_from: null
allow_partial_load: false
pretrained_dreamforge: ./pretrained/dreamforge-s
train_with_same_noise_t: false
video_length: 7
ref_length: 2
sc_attn_index:
  - [0, 0]  # keyframe
  - [0, 0]
  - [0, 1]
  - [0, 2]
  - [0, 3]
  - [0, 4]
  - [0, 5]  # keyframe

runner_module: dreamforge.runner.multiview_t_runner.MultiviewTRunner

pipe_module: dreamforge.pipeline.pipeline_bev_controlnet_t.StableDiffusionBEVControlNetTPipeline

unet_module: dreamforge.networks.unet_2d_condition_multiview_st.UNet2DConditionModelMultiviewSceneT
use_fp32_for_unet_trainable: true
unet_dir: unet
unet:
  video_length: ${..video_length}
  temp_pos_emb: learnable
  zero_module_type2: zero_linear
  spatial_trainable: false
  with_ref: true
  ref_length: ${..ref_length}
  with_can_bus: true
  with_motion: true

model_module: dreamforge.networks.unet_addon_rawbox.BEVControlNetModel
controlnet_dir: controlnet
controlnet: {}

scene_embedder_cls: dreamforge.networks.scene_position_embedder.ScenePositionEmbedding
scene_embedder_dir: scene_embedder
scene_embedder:
  embed_dims: 320
  LID: false

can_bus_embedder_cls: dreamforge.networks.can_bus_embedder.CanbusEmbedding
can_bus_embedder_dir: can_bus_embedder
can_bus_embedder: 
  embed_dims: 768
  input_channels: 9
  can_bus_norm: true
