defaults:
  - config
  - _self_

log_root_prefix: ./work_dirs/dreamforge-t-log/test
task_id: 2.0t_0.3.3

runner:
  validation_batch_size: 1
  validation_times: 1
  pipeline_param:
    init_noise: rand_all

dataset:
  dataset_type: NuScenesMapDataset
  dataset_cache_file_tag: 8x200x200_12Hz_interp
  dataset_cache_dirname: nuscenes_map_aux_12Hz_interp
  dataset_process_root: ./data/nuscenes_mmdet3d-12Hz_description/
  data:
    train:
      ann_file: ${...dataset_process_root}nuscenes_interp_12Hz_updated_description_train.pickle
      start_on_keyframe: false
    val:
      ann_file: ${...dataset_process_root}nuscenes_interp_12Hz_updated_description_val.pickle
      start_on_keyframe: false
    test:
      ann_file: ${...dataset_process_root}nuscenes_interp_12Hz_updated_description_val.pickle
      start_on_keyframe: false

resume_on_exists: false
show_box: true
cloud: false
fps: 2

fix_seed_for_every_generation: False
