defaults:
  - dataset: ../Nuscenes
  - _self_

seed: 42

dataset:
  dataset_type_nuscenes: NuScenesDataset
  dataset_process_root_nuscenes: data/nuscenes_mmdet3d-12Hz_description/
  data:
    train:
      nuscenes:
        ann_file: ${....dataset_process_root_nuscenes}nuscenes_interp_12Hz_updated_description_train.pkl
    val:
      nuscenes:
        ann_file: ${....dataset_process_root_nuscenes}nuscenes_interp_12Hz_updated_description_val.pkl
    test:
      nuscenes:
        ann_file: ${....dataset_process_root_nuscenes}nuscenes_interp_12Hz_updated_description_val.pkl
