# @package _global_
defaults:
  - /dataset/Nuplan
  - _self_

video_length: 7

dataset:
  dataset_type: NuPlanMapDataset
  dataset_process_root: data/nuplan/
  dataset_cache_file_tag: nuplan_map_aux
  dataset_cache_dirname: nuplan
  dataset_cache_file:
    - ${..dataset_process_root}../${..dataset_cache_dirname}/train_${..dataset_cache_file_tag}.h5
    - ${..dataset_process_root}../${..dataset_cache_dirname}/val_${..dataset_cache_file_tag}.h5
  data:
    train:
      nuplan:
        ann_file: ${....dataset_process_root}nuplan_infos_train.pkl
        map_bound: ${....map_bound}
        video_length: ${video_length}
        start_on_keyframe: False
        fps: 12
    val:
      nuplan:
        ann_file: ${....dataset_process_root}nuplan_infos_val.pkl
        map_bound: ${....map_bound}
        video_length: ${video_length}
        start_on_keyframe: False
        fps: 12
    test:
      nuplan:
        ann_file: ${....dataset_process_root}nuplan_infos_val.pkl
        map_bound: ${....map_bound}
        video_length: ${video_length}
        fps: 2
