# @package _global_
defaults:
  - /dataset/Nuscenes
  - _self_

video_length: 7

dataset:
  dataset_type_nuscenes: NuScenesMapDataset
  dataset_process_root_nuscenes: data/nuscenes_mmdet3d-12Hz_description/
  dataset_cache_file_tag_nuscenes: 200x200_12Hz_interp
  dataset_cache_dirname_nuscenes: nuscenes_map_aux_12Hz_interp
  dataset_cache_file_nuscenes:
    - ${..dataset_process_root_nuscenes}../${..dataset_cache_dirname_nuscenes}/train_${..dataset_cache_file_tag_nuscenes}.h5
    - ${..dataset_process_root_nuscenes}../${..dataset_cache_dirname_nuscenes}/val_${..dataset_cache_file_tag_nuscenes}.h5
  data:
    train:
      nuscenes:
        ann_file: ${....dataset_process_root_nuscenes}nuscenes_interp_12Hz_updated_description_train.pkl
        map_bound: ${....map_bound}
        video_length: ${video_length}
        start_on_keyframe: False
        fps: 12
    val:
      nuscenes:
        ann_file: ${....dataset_process_root_nuscenes}nuscenes_interp_12Hz_updated_description_val.pkl
        map_bound: ${....map_bound}
        video_length: ${video_length}
        start_on_keyframe: False
        fps: 12
    test:
      nuscenes:
        ann_file: ${....dataset_process_root_nuscenes}nuscenes_interp_12Hz_updated_description_val.pkl
        map_bound: ${....map_bound}
        video_length: ${video_length}
        fps: 2
