# Server Configuration
servers:
  diffusion: "http://127.0.0.1:11000/"
  driver: "http://127.0.0.1:11001/"

# Simulation Configuration
simulation:
  ego_id: '228'
  step_length: 0.1
  gui_display: true
  max_sim_time: 120
  use_agent_path: false # false for open-loop, true for closed-loop

agent: uniad

# Map Configuration
map:
  name: 'singapore-onenorth'
  gen_description: 'A driving scene image at singapore. daytime, sunny, downtown'
  sumo_cfg_file: "networkFiles/{map_name}/osm.sumocfg"
  sumo_net_file: "networkFiles/{map_name}/osm.net.xml"
  sumo_rou_file: "networkFiles/{map_name}/osm.rou.xml"

# Data Configuration
data:
  template_path: "data/data_template.pth"
  nu_scenes_root: "networkFiles/{map_name}/"

# Image Configuration
image:
  size: 200
  target_size: [560, 315]