# @package _global_
defaults:
  - /dataset/Nuscenes_map_cache_box_t
  # - /runner/default_t
  - model: ../../model/SDv1.5mv_rawbox_t
  - _self_  # make sure override

# NOTE: we do not handle map explicitly, since on cache miss, our code can get
# the map from whole nuscenes map correctly. Therefore, we assume map is always
# available to every frame.

# based on 0.1.3, use non-key frames
task_id: 2.0t_0.3.3
log_root_prefix: ./work_dirs/dreamforge-t-448x800-log
runner:
    # validation_index: [204, 899, 1828, 3090] # total 4969
    validation_index: [138, 632, 1301, 2342] # should match above
    validation_before_run: false
    validation_steps: 40000
    max_train_steps: 30000
    enable_unet_checkpointing: true
    enable_controlnet_checkpointing: true
    pipeline_param:
      keyframe_rate: 6
    save_model_per_epoch: 10
dataset:
  image_size: [448, 800]
  augment2d:
    resize: [[0.5, 0.5]]
  dataset_root: ./data/nuscenes
  dataset_type: NuScenesMapDataset
  dataset_cache_file_tag: 8x200x200_12Hz_interp
  dataset_cache_dirname: nuscenes_map_aux_12Hz_interp
  dataset_process_root: ./data/nuscenes_mmdet3d-12Hz_description/
  start_on_keyframe: true
  data:
    train:
      ann_file: ${...dataset_process_root}nuscenes_interp_12Hz_updated_description_train.pickle
      video_length: ${model.video_length}
      start_on_keyframe: ${dataset.start_on_keyframe}
      ref_length: ${model.ref_length}
      candidate_length: 5 
    val:
      ann_file: ${...dataset_process_root}nuscenes_interp_12Hz_updated_description_val.pickle
      video_length: ${model.video_length}
      start_on_keyframe: ${dataset.start_on_keyframe}
      ref_length: ${model.ref_length}
      candidate_length: 5
    test:
      ann_file: ${...dataset_process_root}nuscenes_interp_12Hz_updated_description_val.pickle
      video_length: ${model.video_length}
      start_on_keyframe: ${dataset.start_on_keyframe}
      ref_length: ${model.ref_length}
      candidate_length: 5
      
model:
  fix_controlnet: false
  pretrained_dreamforge: ./pretrained/dreamforge-t-336x600
  sc_attn_index:
    - [0, 6, 0]  # keyframe
    - [0, 6, 0]
    - [0, 6, 1]
    - [0, 6, 2]
    - [0, 6, 3]
    - [0, 6, 4]
    - [0, 6, 5]  # keyframe
  unet:
    transformer_type: _ff_last  # tune-a-video
    zero_module_type2: none
    spatial_trainable: true

  controlnet:
    map_embedder_cls: dreamforge.networks.map_embedder.BEVControlNetConditioningEmbedding
    map_embedder_param: 
      conditioning_size: ${..map_size}
      block_out_channels: ${..conditioning_embedding_out_channels}
      output_size: [56, 100]

  scene_embedder:
    output_size: [56, 100]