defaults:
  - model: SDv1.5_mv_single_ref
  - dataset: [Nuscenes_12hz, Nuplan_12hz] 
  - accelerator: default
  - runner: default
  - _self_


task_id: "224x400"
log_root_prefix: ./dreamer-log
projname: ${model.name}
hydra:
  run:
    dir: ${log_root_prefix}/${projname}_${now:%Y-%m-%d}_${now:%H-%M}_${task_id}
  output_subdir: hydra

try_run: false
debug: false
log_root: ???
seed: 42
fix_seed_within_batch: false

resume_from_checkpoint: null
resume_reset_scheduler: false
validation_only: false
validation_steps: 5000
checkpointing_steps: 50000
save_model_per_epoch: 5

runner:
  validation_index: [0, 100, 200, 300, 400, 500, 600, 700, 899, 1828, 3090]