defaults:
  - config
  - _self_

log_root_prefix: ./dreamer-log/test

runner:
  validation_batch_size: 1    # now we only support 1 
  validation_times: 1
  validation_index: all    # can be 'all' or 'demo' or a list of index like [100, 200, 300]

show_box_on_img: true
show_map_on_img: true
transparent_bg: False
seed: 42
fix_seed_for_every_generation: False
start: 0
end: 6019
resume_from_checkpoint: null

dataset:
  data:
    val:
      nuscenes:
        start_on_keyframe: True
        fps: 2
